name: workflow

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with: { go-version: 1.16.5 }

    - name: Install Packer
      uses: hashicorp-contrib/setup-packer@v1
      with: { packer-version: 1.7.3 }

    - name: Install Ansible
      run: pip install ansible

    - name: Install Taskfile
      run: curl -sL https://taskfile.dev/install.sh | sh

    - name: Run tests
      run: ./bin/task install-dependencies
